name: grand_hotel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  google_fonts: ^6.3.0
  cached_network_image: ^3.4.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  shared_preferences: ^2.5.3
  get: ^4.7.2
  loading_animation_widget: ^1.3.0
  shimmer: ^3.0.0
  image_picker: ^1.2.0
  http: ^1.5.0
  path: ^1.9.0
  permission_handler: ^12.0.1
  timeago: ^3.7.1
  fl_chart: ^1.1.0
  url_launcher: ^6.3.2
  toastification: ^3.0.3
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  flutter_svg: ^2.2.1
  google_maps_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Build runner va freezed dev dependencies bo'lishi kerak
  build_runner: ^2.4.15
  freezed: ^3.0.6
  flutter_native_splash: ^2.4.7

# Flutter Native Splash Configuration
flutter_native_splash:
  color: "#3B5BA5"
  image: assets/images/splash_screen.png

  android: true
  android_gravity: center

  android_12:
    color: "#3B5BA5"
    image: assets/images/splash_screen.png
    icon_background_color: "#3B5BA5"

  ios: true
  ios_content_mode: center

  web: false
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # Fonts (agar kerak bo'lsa)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700